2023-09-14 15:10:55,572 INFO    MainThread:819 [wandb_setup.py:_flush():76] Current SDK version is 0.15.9
2023-09-14 15:10:55,572 INFO    MainThread:819 [wandb_setup.py:_flush():76] Configure stats pid to 819
2023-09-14 15:10:55,573 INFO    MainThread:819 [wandb_setup.py:_flush():76] Loading settings from /home/chengp1/.config/wandb/settings
2023-09-14 15:10:55,573 INFO    MainThread:819 [wandb_setup.py:_flush():76] Loading settings from /notebooks/rl2023/ex1/wandb/settings
2023-09-14 15:10:55,573 INFO    MainThread:819 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-14 15:10:55,573 INFO    MainThread:819 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-14 15:10:55,573 INFO    MainThread:819 [wandb_init.py:_log_setup():524] Logging user logs to /notebooks/rl2023/ex1/wandb/run-20230914_151055-ntraj93c/logs/debug.log
2023-09-14 15:10:55,573 INFO    MainThread:819 [wandb_init.py:_log_setup():525] Logging internal logs to /notebooks/rl2023/ex1/wandb/run-20230914_151055-ntraj93c/logs/debug-internal.log
2023-09-14 15:10:55,573 INFO    MainThread:819 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc2e244ada0>
2023-09-14 15:10:55,574 INFO    MainThread:819 [wandb_init.py:init():564] calling init triggers
2023-09-14 15:10:55,574 INFO    MainThread:819 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'entries': {'exp_name': 'ex1', 'seed': None, 'env_name': 'TargetReacher-v0', 'max_episode_steps': 200, 'train_episodes': 200, 'batch_size': 64, 'min_update_samples': 2000, 'testing': False, 'model_path': 'default', 'save_video': True, 'save_model': True, 'save_logging': True, 'silent': False, 'use_wandb': True, 'run_suffix': 0}, 'exp_name': 'ex1', 'seed': None, 'env_name': 'TargetReacher-v0', 'max_episode_steps': 200, 'train_episodes': 200, 'batch_size': 64, 'min_update_samples': 2000, 'testing': False, 'model_path': 'default', 'save_video': True, 'save_model': True, 'save_logging': True, 'silent': False, 'use_wandb': True, 'run_suffix': 0}
2023-09-14 15:10:55,574 INFO    MainThread:819 [wandb_init.py:init():613] starting backend
2023-09-14 15:10:55,574 INFO    MainThread:819 [wandb_init.py:init():617] setting up manager
2023-09-14 15:10:55,577 INFO    MainThread:819 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-09-14 15:10:55,577 INFO    MainThread:819 [wandb_init.py:init():623] backend started and connected
2023-09-14 15:10:55,590 INFO    MainThread:819 [wandb_run.py:_label_probe_notebook():1234] probe notebook
2023-09-14 15:10:55,590 INFO    MainThread:819 [wandb_run.py:_label_probe_notebook():1244] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-09-14 15:10:55,590 INFO    MainThread:819 [wandb_init.py:init():714] updated telemetry
2023-09-14 15:10:55,591 INFO    MainThread:819 [wandb_init.py:init():747] communicating run to backend with 60.0 second timeout
2023-09-14 15:11:55,636 ERROR   MainThread:819 [wandb_init.py:init():773] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-09-14 15:11:55,746 ERROR   MainThread:819 [wandb_init.py:init():1182] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/opt/software/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    run = wi.init()
  File "/opt/software/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-09-14 15:13:30,528 INFO    MainThread:819 [wandb_setup.py:_flush():76] Current SDK version is 0.15.9
2023-09-14 15:13:30,529 INFO    MainThread:819 [wandb_setup.py:_flush():76] Configure stats pid to 819
2023-09-14 15:13:30,529 INFO    MainThread:819 [wandb_setup.py:_flush():76] Loading settings from /home/chengp1/.config/wandb/settings
2023-09-14 15:13:30,530 INFO    MainThread:819 [wandb_setup.py:_flush():76] Loading settings from /notebooks/rl2023/ex1/wandb/settings
2023-09-14 15:13:30,530 INFO    MainThread:819 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-14 15:13:30,530 INFO    MainThread:819 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-14 15:13:30,530 INFO    MainThread:819 [wandb_init.py:_log_setup():524] Logging user logs to /notebooks/rl2023/ex1/wandb/run-20230914_151330-3bbpqai9/logs/debug.log
2023-09-14 15:13:30,530 INFO    MainThread:819 [wandb_init.py:_log_setup():525] Logging internal logs to /notebooks/rl2023/ex1/wandb/run-20230914_151330-3bbpqai9/logs/debug-internal.log
2023-09-14 15:13:30,530 INFO    MainThread:819 [wandb_init.py:init():564] calling init triggers
2023-09-14 15:13:30,530 INFO    MainThread:819 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'entries': {'exp_name': 'ex1', 'seed': None, 'env_name': 'TargetReacher-v0', 'max_episode_steps': 200, 'train_episodes': 200, 'batch_size': 64, 'min_update_samples': 2000, 'testing': False, 'model_path': 'default', 'save_video': True, 'save_model': True, 'save_logging': True, 'silent': False, 'use_wandb': True, 'run_suffix': 0}, 'exp_name': 'ex1', 'seed': None, 'env_name': 'TargetReacher-v0', 'max_episode_steps': 200, 'train_episodes': 200, 'batch_size': 64, 'min_update_samples': 2000, 'testing': False, 'model_path': 'default', 'save_video': True, 'save_model': True, 'save_logging': True, 'silent': False, 'use_wandb': True, 'run_suffix': 0}
2023-09-14 15:13:30,531 INFO    MainThread:819 [wandb_init.py:init():613] starting backend
2023-09-14 15:13:30,531 INFO    MainThread:819 [wandb_init.py:init():617] setting up manager
2023-09-14 15:13:30,533 INFO    MainThread:819 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-09-14 15:13:30,534 INFO    MainThread:819 [wandb_init.py:init():623] backend started and connected
2023-09-14 15:13:30,544 INFO    MainThread:819 [wandb_run.py:_label_probe_notebook():1234] probe notebook
2023-09-14 15:13:30,544 INFO    MainThread:819 [wandb_run.py:_label_probe_notebook():1244] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-09-14 15:13:30,544 INFO    MainThread:819 [wandb_init.py:init():714] updated telemetry
2023-09-14 15:13:30,545 INFO    MainThread:819 [wandb_init.py:init():747] communicating run to backend with 60.0 second timeout
2023-09-14 15:14:30,588 ERROR   MainThread:819 [wandb_init.py:init():773] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-09-14 15:14:30,627 ERROR   MainThread:819 [wandb_init.py:init():1182] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/opt/software/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    run = wi.init()
  File "/opt/software/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-09-14 15:15:52,442 INFO    MainThread:819 [wandb_setup.py:_flush():76] Current SDK version is 0.15.9
2023-09-14 15:15:52,445 INFO    MainThread:819 [wandb_setup.py:_flush():76] Configure stats pid to 819
2023-09-14 15:15:52,445 INFO    MainThread:819 [wandb_setup.py:_flush():76] Loading settings from /home/chengp1/.config/wandb/settings
2023-09-14 15:15:52,445 INFO    MainThread:819 [wandb_setup.py:_flush():76] Loading settings from /notebooks/rl2023/ex1/wandb/settings
2023-09-14 15:15:52,445 INFO    MainThread:819 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-14 15:15:52,445 INFO    MainThread:819 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-14 15:15:52,446 INFO    MainThread:819 [wandb_init.py:_log_setup():524] Logging user logs to /notebooks/rl2023/ex1/wandb/run-20230914_151552-br3q27zb/logs/debug.log
2023-09-14 15:15:52,446 INFO    MainThread:819 [wandb_init.py:_log_setup():525] Logging internal logs to /notebooks/rl2023/ex1/wandb/run-20230914_151552-br3q27zb/logs/debug-internal.log
2023-09-14 15:15:52,446 INFO    MainThread:819 [wandb_init.py:init():564] calling init triggers
2023-09-14 15:15:52,446 INFO    MainThread:819 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'entries': {'exp_name': 'ex1', 'seed': None, 'env_name': 'TargetReacher-v0', 'max_episode_steps': 200, 'train_episodes': 200, 'batch_size': 64, 'min_update_samples': 2000, 'testing': False, 'model_path': 'default', 'save_video': True, 'save_model': True, 'save_logging': True, 'silent': False, 'use_wandb': True, 'run_suffix': 0}, 'exp_name': 'ex1', 'seed': None, 'env_name': 'TargetReacher-v0', 'max_episode_steps': 200, 'train_episodes': 200, 'batch_size': 64, 'min_update_samples': 2000, 'testing': False, 'model_path': 'default', 'save_video': True, 'save_model': True, 'save_logging': True, 'silent': False, 'use_wandb': True, 'run_suffix': 0}
2023-09-14 15:15:52,446 INFO    MainThread:819 [wandb_init.py:init():613] starting backend
2023-09-14 15:15:52,446 INFO    MainThread:819 [wandb_init.py:init():617] setting up manager
2023-09-14 15:15:52,449 INFO    MainThread:819 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-09-14 15:15:52,449 INFO    MainThread:819 [wandb_init.py:init():623] backend started and connected
2023-09-14 15:15:52,460 INFO    MainThread:819 [wandb_run.py:_label_probe_notebook():1234] probe notebook
2023-09-14 15:15:52,460 INFO    MainThread:819 [wandb_run.py:_label_probe_notebook():1244] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-09-14 15:15:52,460 INFO    MainThread:819 [wandb_init.py:init():714] updated telemetry
2023-09-14 15:15:52,461 INFO    MainThread:819 [wandb_init.py:init():747] communicating run to backend with 60.0 second timeout
2023-09-14 15:16:52,504 ERROR   MainThread:819 [wandb_init.py:init():773] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-09-14 15:16:52,543 ERROR   MainThread:819 [wandb_init.py:init():1182] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/opt/software/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    run = wi.init()
  File "/opt/software/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
